define(function(require,exports,module){
  var sites=[];
  sites.push(require('./1'));
  sites.push(require('./2'));
  sites.push(require('./3'));
  sites.push(require('./4'));
//  sites.push(require('./5'));
  sites.push(require('./6'));
  sites.push(require('./7'));
  sites.push(require('./8'));
  sites.push(require('./9'));
  sites.push(require('./10'));
  sites.push(require('./11'));
//  sites.push(require('./12'));
  sites.push(require('./13'));
  sites.push(require('./14'));
  sites.push(require('./15'));
  sites.push(require('./16'));
  sites.push(require('./17'));
//  sites.push(require('./18'));
  sites.push(require('./19'));
//  sites.push(require('./20'));
  sites.push(require('./21'));
//  sites.push(require('./22'));
//  sites.push(require('./23'));
  sites.push(require('./24'));
//  sites.push(require('./25'));
//  sites.push(require('./26'));
  sites.push(require('./27'));
  sites.push(require('./28'));
//  sites.push(require('./29'));
  sites.push(require('./30'));
  sites.push(require('./31'));
  sites.push(require('./32'));
  sites.push(require('./33'));
  sites.push(require('./34'));
//  sites.push(require('./35'));
  sites.push(require('./36'));
  sites.push(require('./37'));
  sites.push(require('./38'));
  sites.push(require('./39'));
//  sites.push(require('./40'));
//  sites.push(require('./41'));
//  sites.push(require('./42'));
  sites.push(require('./43'));
  sites.push(require('./44'));
  sites.push(require('./45'));
  sites.push(require('./46'));
//  sites.push(require('./47'));
//  sites.push(require('./48'));
//  sites.push(require('./49'));
  sites.push(require('./50'));
  sites.push(require('./51'));
  sites.push(require('./52'));
  sites.push(require('./53'));
//  sites.push(require('./54'));
//  sites.push(require('./55'));
  sites.push(require('./56'));
  sites.push(require('./57'));
  sites.push(require('./58'));
  sites.push(require('./59'));
  sites.push(require('./60'));
  sites.push(require('./61'));
  sites.push(require('./62'));
//  sites.push(require('./63'));
  sites.push(require('./64'));
  sites.push(require('./65'));
  sites.push(require('./66'));
  sites.push(require('./67'));
//  sites.push(require('./68'));
//  sites.push(require('./69'));
  sites.push(require('./70'));
  sites.push(require('./71'));
  sites.push(require('./72'));
  sites.push(require('./73'));
//  sites.push(require('./74'));
//  sites.push(require('./75'));
//  sites.push(require('./76'));
  sites.push(require('./77'));
  sites.push(require('./78'));
  sites.push(require('./79'));
  sites.push(require('./80'));
  sites.push(require('./81'));
  sites.push(require('./82'));
//	sites.push(require('./83'));
	sites.push(require('./84'));
//	sites.push(require('./85'));
	sites.push(require('./86'));
	sites.push(require('./87'));
	sites.push(require('./88'));
	sites.push(require('./89'));
	sites.push(require('./90'));
	sites.push(require('./91'));
	sites.push(require('./92'));
//	sites.push(require('./93'));
//	sites.push(require('./94'));
	sites.push(require('./95'));
	sites.push(require('./96'));
	sites.push(require('./97'));
//	sites.push(require('./98'));
	sites.push(require('./99'));
//	sites.push(require('./100'));
//	sites.push(require('./101'));
//	sites.push(require('./102'));
	sites.push(require('./103'));
//	sites.push(require('./104'));
	sites.push(require('./105'));
	sites.push(require('./106'));
//	sites.push(require('./107'));
	sites.push(require('./108'));
//	sites.push(require('./109'));
//	sites.push(require('./110'));
//	sites.push(require('./111'));
	sites.push(require('./112'));
//	sites.push(require('./113'));
//	sites.push(require('./114'));
	sites.push(require('./115'));
	sites.push(require('./116'));
	sites.push(require('./117'));
	sites.push(require('./118'));
	sites.push(require('./119'));
	sites.push(require('./120'));
//	sites.push(require('./121'));
	sites.push(require('./122'));
	sites.push(require('./123'));
//	sites.push(require('./124'));
//	sites.push(require('./125'));
	sites.push(require('./127'));
	sites.push(require('./128'));
	sites.push(require('./129'));
	sites.push(require('./130'));
	sites.push(require('./131'));
//	sites.push(require('./132'));
	sites.push(require('./133'));
	sites.push(require('./134'));
	sites.push(require('./135'));
	sites.push(require('./136'));
	sites.push(require('./137'));
  module.exports=sites;
});